# Generated by Django 2.2 on 2020-08-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
