# Generated by Django 2.2 on 2020-08-29 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0004_auto_20200829_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='car',
        ),
    ]
