# Generated by Django 2.2 on 2020-08-28 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0003_user_bio'),
        ('Dashboard', '0002_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chassis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255, null=True)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('engine', models.CharField(max_length=255)),
                ('drivetrain', models.CharField(max_length=255)),
                ('hp', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('car_pic', models.CharField(max_length=255, null=True)),
                ('car', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owns', to='log_reg_app.User')),
            ],
        ),
    ]
