# Generated by Django 2.2 on 2020-08-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_chassis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chassis',
            name='car',
        ),
        migrations.AlterField(
            model_name='chassis',
            name='car_pic',
            field=models.ImageField(null=True, upload_to='cars'),
        ),
    ]
