# Generated by Django 2.2 on 2020-08-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0005_remove_user_car'),
        ('Dashboard', '0004_auto_20200828_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chassis',
            name='owner',
        ),
        migrations.AddField(
            model_name='chassis',
            name='owner',
            field=models.ManyToManyField(related_name='owns', to='log_reg_app.User'),
        ),
    ]
