# Generated by Django 2.2 on 2020-08-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_auto_20200829_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='owner',
            field=models.ManyToManyField(null=True, related_name='owns', to='log_reg_app.User'),
        ),
    ]
