# Generated by Django 2.2 on 2020-08-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_auto_20200831_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='owns', to='log_reg_app.User'),
        ),
    ]
